version: '3'

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - mongo-vol:/bitnami

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/bitnami
    depends_on:
      - fix-mongodb-permissions

  communication-server:
    # image: registry.gitlab.com/castlecraft/building-blocks/communication-server:latest
    image: communication-server:latest
    ports:
      - "4100:4100"
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - communication-server-vol:/home/craft/communication-server/files

volumes:
  mongo-vol:
  communication-server-vol:
