version: '3'

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - mongo-vol:/bitnami

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    volumes:
      - mongo-vol:/bitnami
    depends_on:
      - fix-mongodb-permissions

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=admin
    volumes:
      - redis-vol:/bitnami/redis/data

  communication-server:
    image: registry.gitlab.com/castlecraft/building-blocks/communication-server:testing
    ports:
      - "4100:4100"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin

volumes:
  mongo-vol:
  redis-vol:
