version: '3'

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - mongo-vol:/bitnami

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/bitnami
    depends_on:
      - fix-mongodb-permissions

  eventstore:
    image: eventstore/eventstore:latest
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
    volumes:
      - eventstore-vol:/var/lib/eventstore

  authorization-service:
    image: registry.gitlab.com/castlecraft/building-blocks/authorization-server:edge
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - eventstore
    links:
      - mongo
      - eventstore
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - EXPIRY_DAYS=${EXPIRY_DAYS}
      - COOKIE_MAX_AGE=${COOKIE_MAX_AGE}
      - SESSION_NAME=${SESSION_NAME}
      - TOKEN_VALIDITY=${TOKEN_VALIDITY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - ES_HOST=${ES_HOST}
      - ES_USER=${ES_USER}
      - ES_PASSWORD=${ES_PASSWORD}
      - ES_STREAM=${ES_STREAM}

volumes:
  mongo-vol:
  eventstore-vol:
