version: '3'

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - mongo-vol:/bitnami

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/bitnami
    depends_on:
      - fix-mongodb-permissions

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-vol:/data

  authorization-service:
    # image: registry.gitlab.com/castlecraft/building-blocks/authorization-server:latest
    image: authorization-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - EXPIRY_DAYS=${EXPIRY_DAYS}
      - COOKIE_MAX_AGE=${COOKIE_MAX_AGE}
      - SESSION_NAME=${SESSION_NAME}
      - TOKEN_VALIDITY=${TOKEN_VALIDITY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BULL_QUEUE_REDIS_HOST=${BULL_QUEUE_REDIS_HOST}
      - BULL_QUEUE_REDIS_PORT=${BULL_QUEUE_REDIS_PORT}
      - NODE_ENV=${NODE_ENV}

volumes:
  redis-vol:
  mongo-vol:
