apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: mongodb
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: registry.gitlab.com/castlecraft/docker-craft/debian-mongodb-mongodump:latest
            env:
              - name: "MONGODB_HOST"
                value: global-mongodb.mongodb.svc.cluster.local
              - name: "ARCHIVE_PREFIX"
                value: backups
              - name: "REGION"
                value: US
              - name: "STORAGE_HOST"
                value: bucket.host.tld
              - name: "BUCKET"
                value: bucketname
              - name: "MONGODB_ROOT_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    key: mongodb-root-password
                    name: global-mongodb
              - name: "ACCESS_KEY"
                valueFrom:
                  secretKeyRef:
                    key:  accessKey
                    name: s3-secrets
              - name: "SECRET_KEY"
                valueFrom:
                  secretKeyRef:
                    key:  secretKey
                    name: s3-secrets
          restartPolicy: Never
      backoffLimit: 4

---

apiVersion: v1
data:
  accessKey: YWNjZXNzX2tleQo=
  secretKey: c2VjcmV0X2tleQo==
kind: Secret
metadata:
  name: s3-secrets
  namespace: mongodb
type: Opaque
