dependencies:
- name: mongodb
  version: 4.9.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 5.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
