apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-events
data:
  {{- if .Values.mqtt.password }}
  events-password:  {{ .Values.mqtt.password | b64enc | quote }}
  {{- else }}
  events-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
