version: "3.7"

services:
  # Frontend
  authorization-client:
    image: registry.gitlab.com/castlecraft/building-blocks/authorization-client:edge
    environment:
      - API_HOST=authorization-server
      - API_PORT=3000
    ports:
      - 4210:8080

  admin-client:
    image: registry.gitlab.com/castlecraft/building-blocks/admin-client:edge
    environment:
      - API_HOST=infrastructure-console
      - API_PORT=5000
    ports:
      - 4220:8080

  identity-client:
    image: registry.gitlab.com/castlecraft/building-blocks/identity-client:edge
    environment:
      - API_HOST=identity-provider
      - API_PORT=3200
    ports:
      - 4420:8080

  # Backend
  authorization-server:
    image: registry.gitlab.com/castlecraft/building-blocks/authorization-server:latest
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=changeit
      - COOKIE_MAX_AGE=7.884e+9
      - SESSION_NAME=bb-io
      - TOKEN_VALIDITY=3600
      - DB_HOST=mongo
      - DB_NAME=authorization-server
      - DB_USER=authorization-server
      - DB_PASSWORD=changeit
      - REDIS_HOST=redis-event-bus
      - REDIS_PASSWORD=changeit
      - REDIS_PORT=6379
      - REDIS_PROTO=redis

  communication-server:
    image: registry.gitlab.com/castlecraft/building-blocks/communication-server:latest
    environment:
      - NODE_ENV=development
      - DB_HOST=mongo
      - DB_NAME=communication-server
      - DB_USER=communication-server
      - DB_PASSWORD=changeit
      - REDIS_HOST=redis-event-bus
      - REDIS_PASSWORD=changeit
      - REDIS_PORT=6379
      - REDIS_PROTO=redis
    ports:
      - 4100:4100

  identity-provider:
    image: registry.gitlab.com/castlecraft/building-blocks/identity-provider:latest
    environment:
      - NODE_ENV=development
      - DB_HOST=mongo
      - DB_NAME=identity-provider
      - DB_USER=identity-provider
      - DB_PASSWORD=changeit
      - REDIS_HOST=redis-event-bus
      - REDIS_PASSWORD=changeit
      - REDIS_PORT=6379
      - REDIS_PROTO=redis

  infrastructure-console:
    image: registry.gitlab.com/castlecraft/building-blocks/infrastructure-console:latest
    environment:
      - NODE_ENV=development
      - DB_HOST=mongo
      - DB_NAME=infrastructure-console
      - DB_USER=infrastructure-console
      - DB_PASSWORD=changeit
      - REDIS_HOST=redis-event-bus
      - REDIS_PASSWORD=changeit
      - REDIS_PORT=6379
      - REDIS_PROTO=redis

  # Services
  redis-event-bus:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=changeit

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - "MONGODB_ROOT_PASSWORD=changeit"
      - "MONGODB_DATABASE=authorization-server"
      - "MONGODB_USERNAME=authorization-server"
      - "MONGODB_PASSWORD=changeit"
    volumes:
      - mongodb-vol:/bitnami/mongodb

  mongo-configuration:
    image: bitnami/mongodb:latest
    command:
      - bash
      - -c
      - >
        sleep 10;
        mongo identity-provider \
          --host mongo \
          --port 27017 \
          -u root \
          -p changeit \
          --authenticationDatabase admin \
          --eval "db.createUser({user: 'identity-provider', pwd: 'changeit', roles:[{role:'dbOwner', db: 'identity-provider'}]});";

        mongo infrastructure-console \
          --host mongo \
          --port 27017 \
          -u root \
          -p changeit \
          --authenticationDatabase admin \
          --eval "db.createUser({user: 'infrastructure-console', pwd: 'changeit', roles:[{role:'dbOwner', db: 'infrastructure-console'}]});";

        mongo communication-server \
          --host mongo \
          --port 27017 \
          -u root \
          -p changeit \
          --authenticationDatabase admin \
          --eval "db.createUser({user: 'communication-server', pwd: 'changeit', roles:[{role:'dbOwner', db: 'communication-server'}]});";

volumes:
  mongodb-vol:
