version: "3"

services:
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD={$REDIS_PASSWORD}
    volumes:
      - redis-vol:/bitnami/redis/data

volumes:
  redis-vol:
