version: "3"

services:
  # Frontend
  authorization-client:
    # image: registry.gitlab.com/castlecraft/building-blocks/authorization-client:latest
    build: 
      context: ../frontends/authorization-client
      dockerfile: Dockerfile
    environment:
      - API_HOST=authorization-server
      - API_PORT=3000
    ports:
      - 4210:8080

  admin-client:
    # image: registry.gitlab.com/castlecraft/building-blocks/admin-client:latest
    build: 
      context: ../frontends/admin-client
      dockerfile: Dockerfile
    environment:
      - API_HOST=infrastructure-console
      - API_PORT=5000
    ports:
      - 4220:8080

  identity-client:
    # image: registry.gitlab.com/castlecraft/building-blocks/identity-client:latest
    build: 
      context: ../frontends/identity-client
      dockerfile: Dockerfile
    environment:
      - API_HOST=identity-provider
      - API_PORT=3200
    ports:
      - 4420:8080

networks:
  default:
    name: lixi-backend_default
    external: true