{{- $redisEnabled := index .Values "redis-cluster" "enabled" }}
{{- if and (ne .Values.redisHost "") (not $redisEnabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-cluster
data:
  redis-password:  {{ index .Values "redis-cluster" "password" | b64enc | quote }}
{{- end }}
