apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  {{- if .Values.authServer.sessionSecret }}
  SESSION_SECRET: {{ .Values.authServer.sessionSecret | b64enc | quote }}
  {{- else }}
  SESSION_SECRET: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.authServer.dbPassword }}
  AS_DB_PASSWORD:  {{ .Values.authServer.dbPassword| b64enc | quote }}
  {{- else }}
  AS_DB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.comServer.dbPassword }}
  CS_DB_PASSWORD:  {{ .Values.comServer.dbPassword | b64enc | quote }}
  {{- else }}
  CS_DB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.idProvider.dbPassword }}
  IP_DB_PASSWORD:  {{ .Values.idProvider.dbPassword | b64enc | quote }}
  {{- else }}
  IP_DB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.infraConsole.dbPassword }}
  IC_DB_PASSWORD:  {{ .Values.infraConsole.dbPassword | b64enc | quote }}
  {{- else }}
  IC_DB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
