{{- if and .Values.infraConsole.ingress.enabled .Values.infraConsole.enabled -}}
{{- $fullName := include "blocks.fullname" . -}}
{{- $svcPort := .Values.infraConsole.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-infra-console
  labels:
    {{- include "blocks.labels" . | nindent 4 }}
  {{- with .Values.infraConsole.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.infraConsole.ingress.tls }}
  tls:
  {{- range .Values.infraConsole.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.infraConsole.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-infra-console
                port:
                  number: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
