{{- if .Values.infraConsole.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocks.fullname" . }}-infra-console
  labels:
    {{- include "blocks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.infraConsole.service.type }}
  ports:
    - port: {{ .Values.infraConsole.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blocks.infraConsoleSelectorLabels" . | nindent 4 }}
{{- end }}
