apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  user: {{ .Values.rabbitmq.rabbitmq.username }}
  password: {{ .Values.rabbitmq.rabbitmq.password }}
  mongodbPassword: {{ .Values.mongodb.mongodbPassword }}
