dependencies:
- name: mongodb
  version: 4.9.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq
  version: 4.0.1
  repository: https://kubernetes-charts.storage.googleapis.com/
