{{- if .Values.comServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocks.fullname" . }}-com-server
  labels:
    {{- include "blocks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.comServer.service.type }}
  ports:
    - port: {{ .Values.comServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blocks.comServerSelectorLabels" . | nindent 4 }}
{{- end }}
