image: node:8.11.3

cache:
  paths:
  - node_modules/

services:
- mariadb

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: cepl-idp
  MYSQL_ROOT_PASSWORD: mysql_password

before_script:
  - apt-get update -qq
  - apt-get install mysql-client -y -qq
  - echo "use mysql; CREATE USER \`cepl-idp\`@'%' IDENTIFIED BY 'secret';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mariadb
  - echo "GRANT ALL PRIVILEGES ON \`cepl-idp\`.* TO \`cepl-idp\`@'%'; FLUSH PRIVILEGES;" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mariadb

stages:
  - test

test_async:
  stage: test
  script:
   - yarn install
   - yarn lint
   - yarn test
   - yarn test:e2e
  tags:
    - docker
