version: '3'

services:
  database:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    container_name: database

  idp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    stdin_open: true
    tty: true
    container_name: identity-provider
