#!/bin/bash

display_usage() {
  echo "$(basename "$0") [-h] [-c \"<command to be executed inside container>\"]"
  echo ''
  echo 'where:'
  echo '    -h         show this help text'
  echo '    init-sever initializes config and yarn'
  echo '    init-db    initializes database'
  echo '    start      starts server'
}

if [[ $# -eq 0 ]]; then
  docker exec -it identity-provider sh
elif [ $1 == 'start' ]
then
  docker exec -it identity-provider sh -c "yarn start:prod"
elif [ $1 == 'init-server' ]
then
  docker exec -it identity-provider sh -c "yarn"
  docker exec -it identity-provider sh -c "craft server"
elif [ $1 == 'init-db' ]
then
  if [[ -v MYSQL_ROOT_PASSWORD ]]
  then
    docker exec -it identity-provider sh -c "craft database --password $MYSQL_ROOT_PASSWORD --host database"
  else
    echo "MYSQL_ROOT_PASSWORD not set"
  fi
else
  while getopts ':hsc:' option; do
    case "$option" in
      h)
         display_usage
         exit
         ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
  done
fi
